language:       python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=app
  - sudo coverage report -m

after_success:
  - coveralls
  - coverage xml
  - codeclimate-test-reporter

cache:          pip
