language:        python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=app


after_success:
  - coveralls
  - codeclimate-test-reporter
  - codecov

cache:           pip
