language:        python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
    - postgresql

before_script:
    - psql -c "CREATE DATABASE questioner;" -U postgres
    - psql -c "CREATE DATABASE questioner_test;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres
script:
  - pytest
  - pytest --cov=app


after_success:
  - coveralls
  - codecov --token=86e24f0e-2928-4a66-8f48-6fc5cbee8327

cache:           pip
