language:        python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=app


after_success:
  - coveralls
  - codecov --token=86e24f0e-2928-4a66-8f48-6fc5cbee8327

cache:           pip
